targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          sql:
            dialect: sqlite
            options:
              modules:
                - json1
                - fts5