name: cryptowl
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5
  pointycastle: ^3.9.1
  sqlcipher_flutter_libs: ^0.6.4
  sqlite3: ^2.7.3
  kdbx:
    path: ./deps/kdbx.dart
  crypto: ^3.0.6
  uuid: ^4.5.1
  drift: ^2.25.0
  convert: ^3.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  introduction_screen: ^3.1.14
  flutter_svg: ^2.0.17
  vector_graphics: ^1.1.18
  go_router: ^14.8.0
  logging: ^1.3.0
  toastification: ^2.3.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flex_color_scheme: ^8.1.1
  responsive_framework: ^1.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  drift_dev: ^2.25.1
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  faker: ^2.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
  fonts:
    - family:  MyIcons
      fonts:
        - asset: assets/fonts/MyIcons.ttf
    - family: AgileSans
      fonts:
        - asset: assets/fonts/AgileSans-Regular.otf
   