name: cryptowl
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5
  pointycastle: ^3.9.1
  sqlcipher_flutter_libs: ^0.6.4
  sqlite3: ^2.7.3
  kdbx:
    path: ./deps/kdbx.dart
  crypto: ^3.0.6
  uuid: ^4.5.1
  drift: ^2.25.0
  convert: ^3.1.2
  logger: ^2.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
