name: cryptowl
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter 
  flutter_localizations:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5
  pointycastle: ^3.9.1
  sqlcipher_flutter_libs: ^0.6.4
  sqlite3: ^2.7.3
  kdbx:
    path: ./deps/kdbx.dart
  crypto: ^3.0.6
  uuid: ^4.5.1
  drift: ^2.25.0
  convert: ^3.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  introduction_screen: ^3.1.14
  flutter_svg: ^2.0.17
  vector_graphics: ^1.1.18
  go_router: ^15.2.4
  logging: ^1.3.0
  toastification: ^3.0.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flex_color_scheme: ^8.1.1
  responsive_framework: ^1.5.1
  intl: ^0.20.2
  flutter_adaptive_scaffold: ^0.3.2
  package_info_plus: ^8.3.0
  radio_group_v2: ^3.3.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  fleather: ^1.23.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  remixicon: ^1.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  drift_dev: ^2.25.1
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  faker: ^2.2.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
  fonts:
    - family: LXGWWenKai
      fonts:
        - asset: assets/fonts/lxgw-wenkai-v1.520/LXGWWenKai-Light.ttf
          weight: 300
        - asset: assets/fonts/lxgw-wenkai-v1.520/LXGWWenKai-Regular.ttf
          weight: 400
        - asset: assets/fonts/lxgw-wenkai-v1.520/LXGWWenKai-Medium.ttf
          weight: 500
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-4.1/Inter-Thin.otf
          weight: 100
        - asset: assets/fonts/Inter-4.1/Inter-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/Inter-4.1/Inter-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Inter-4.1/Inter-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter-4.1/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-4.1/Inter-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter-4.1/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-4.1/Inter-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-4.1/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-4.1/Inter-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-4.1/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-4.1/Inter-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter-4.1/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-4.1/Inter-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter-4.1/Inter-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Inter-4.1/Inter-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter-4.1/Inter-Black.otf
          weight: 900
        - asset: assets/fonts/Inter-4.1/Inter-BlackItalic.otf
          weight: 900
          style: italic