name: cryptowl
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter 
  flutter_localizations:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5
  sqlite3: ^2.7.3
  ffi: ^2.1.3
  native_argon2:
    path: deps/native_argon2
  native_sqlcipher:
    path: deps/native_sqlcipher
  crypto: ^3.0.6
  uuid: ^4.5.1
  drift: ^2.25.0
  convert: ^3.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  introduction_screen: ^3.1.14
  flutter_svg: ^2.0.17
  vector_graphics: ^1.1.18
  go_router: ^16.0.0
  logging: ^1.3.0
  toastification: ^3.0.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flex_color_scheme: ^8.1.1
  responsive_framework: ^1.5.1
  intl: ^0.20.2
  flutter_adaptive_scaffold: ^0.3.2
  package_info_plus: ^8.3.0
  radio_group_v2: ^3.3.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  fleather: ^1.23.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  remixicon: ^1.4.1
  base32: ^2.2.0
  flutter_secure_storage: ^9.2.4
  file_saver: ^0.3.1
  pdf: ^3.11.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  drift_dev: ^2.25.1
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  faker: ^2.2.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/dict/
  fonts:
    - family: LXGWWenKai
      fonts:
        - asset: assets/fonts/lxgw-wenkai-v1.520/LXGWWenKai-Light.ttf
          weight: 300
        - asset: assets/fonts/lxgw-wenkai-v1.520/LXGWWenKai-Regular.ttf
          weight: 400
        - asset: assets/fonts/lxgw-wenkai-v1.520/LXGWWenKai-Medium.ttf
          weight: 500