// Mocks generated by Mockito 5.4.6 from annotations
// in cryptowl/test/services/app_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i2;
import 'dart:typed_data' as _i10;

import 'package:cryptowl/src/common/protected_value.dart' as _i4;
import 'package:cryptowl/src/config/app_config.dart' as _i6;
import 'package:cryptowl/src/crypto/hkdf.dart' as _i3;
import 'package:cryptowl/src/service/config_service.dart' as _i11;
import 'package:cryptowl/src/service/file_service.dart' as _i7;
import 'package:cryptowl/src/service/kdf_service.dart' as _i9;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFile_0 extends _i1.SmartFake implements _i2.File {
  _FakeFile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCryptoGraphyHkdf_1 extends _i1.SmartFake
    implements _i3.CryptoGraphyHkdf {
  _FakeCryptoGraphyHkdf_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProtectedValue_2 extends _i1.SmartFake
    implements _i4.ProtectedValue {
  _FakeProtectedValue_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterSecureStorage_3 extends _i1.SmartFake
    implements _i5.FlutterSecureStorage {
  _FakeFlutterSecureStorage_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppConfig_4 extends _i1.SmartFake implements _i6.AppConfig {
  _FakeAppConfig_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileService extends _i1.Mock implements _i7.FileService {
  @override
  _i8.Future<List<String>> getSqlcipherInstances() => (super.noSuchMethod(
        Invocation.method(
          #getSqlcipherInstances,
          [],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<_i2.File> getConfigFile() => (super.noSuchMethod(
        Invocation.method(
          #getConfigFile,
          [],
        ),
        returnValue: _i8.Future<_i2.File>.value(_FakeFile_0(
          this,
          Invocation.method(
            #getConfigFile,
            [],
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i2.File>.value(_FakeFile_0(
          this,
          Invocation.method(
            #getConfigFile,
            [],
          ),
        )),
      ) as _i8.Future<_i2.File>);

  @override
  _i8.Future<bool> hasConfigFile() => (super.noSuchMethod(
        Invocation.method(
          #hasConfigFile,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
        returnValueForMissingStub: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> writeConfig(String? content) => (super.noSuchMethod(
        Invocation.method(
          #writeConfig,
          [content],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> writeFile(
    String? content,
    String? fileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeFile,
          [
            content,
            fileName,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [KdfService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKdfService extends _i1.Mock implements _i9.KdfService {
  @override
  _i3.CryptoGraphyHkdf get hkdf => (super.noSuchMethod(
        Invocation.getter(#hkdf),
        returnValue: _FakeCryptoGraphyHkdf_1(
          this,
          Invocation.getter(#hkdf),
        ),
        returnValueForMissingStub: _FakeCryptoGraphyHkdf_1(
          this,
          Invocation.getter(#hkdf),
        ),
      ) as _i3.CryptoGraphyHkdf);

  @override
  _i8.Future<_i4.ProtectedValue> createTransformedMasterKey(
    _i4.ProtectedValue? masterPassword,
    _i4.ProtectedValue? secretKey,
    _i10.Uint8List? salt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTransformedMasterKey,
          [
            masterPassword,
            secretKey,
            salt,
          ],
        ),
        returnValue: _i8.Future<_i4.ProtectedValue>.value(_FakeProtectedValue_2(
          this,
          Invocation.method(
            #createTransformedMasterKey,
            [
              masterPassword,
              secretKey,
              salt,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.ProtectedValue>.value(_FakeProtectedValue_2(
          this,
          Invocation.method(
            #createTransformedMasterKey,
            [
              masterPassword,
              secretKey,
              salt,
            ],
          ),
        )),
      ) as _i8.Future<_i4.ProtectedValue>);

  @override
  _i8.Future<_i4.ProtectedValue> createStretchedMasterKey(
    _i4.ProtectedValue? transformedMasterKey,
    _i10.Uint8List? instanceId,
    _i10.Uint8List? masterSeed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStretchedMasterKey,
          [
            transformedMasterKey,
            instanceId,
            masterSeed,
          ],
        ),
        returnValue: _i8.Future<_i4.ProtectedValue>.value(_FakeProtectedValue_2(
          this,
          Invocation.method(
            #createStretchedMasterKey,
            [
              transformedMasterKey,
              instanceId,
              masterSeed,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.ProtectedValue>.value(_FakeProtectedValue_2(
          this,
          Invocation.method(
            #createStretchedMasterKey,
            [
              transformedMasterKey,
              instanceId,
              masterSeed,
            ],
          ),
        )),
      ) as _i8.Future<_i4.ProtectedValue>);

  @override
  _i8.Future<_i4.ProtectedValue> generateRandomBytes({int? length = 32}) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateRandomBytes,
          [],
          {#length: length},
        ),
        returnValue: _i8.Future<_i4.ProtectedValue>.value(_FakeProtectedValue_2(
          this,
          Invocation.method(
            #generateRandomBytes,
            [],
            {#length: length},
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.ProtectedValue>.value(_FakeProtectedValue_2(
          this,
          Invocation.method(
            #generateRandomBytes,
            [],
            {#length: length},
          ),
        )),
      ) as _i8.Future<_i4.ProtectedValue>);
}

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i11.ConfigService {
  @override
  _i5.FlutterSecureStorage get secureStore => (super.noSuchMethod(
        Invocation.getter(#secureStore),
        returnValue: _FakeFlutterSecureStorage_3(
          this,
          Invocation.getter(#secureStore),
        ),
        returnValueForMissingStub: _FakeFlutterSecureStorage_3(
          this,
          Invocation.getter(#secureStore),
        ),
      ) as _i5.FlutterSecureStorage);

  @override
  _i8.Future<_i6.AppConfig> loadConfig(String? content) => (super.noSuchMethod(
        Invocation.method(
          #loadConfig,
          [content],
        ),
        returnValue: _i8.Future<_i6.AppConfig>.value(_FakeAppConfig_4(
          this,
          Invocation.method(
            #loadConfig,
            [content],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i6.AppConfig>.value(_FakeAppConfig_4(
          this,
          Invocation.method(
            #loadConfig,
            [content],
          ),
        )),
      ) as _i8.Future<_i6.AppConfig>);

  @override
  _i8.Future<_i6.AppConfig> createConfig(
    String? instanceId,
    String? transformSeed,
    String? masterSeed,
    _i4.ProtectedValue? masterPassword,
    _i4.ProtectedValue? secretKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createConfig,
          [
            instanceId,
            transformSeed,
            masterSeed,
            masterPassword,
            secretKey,
          ],
        ),
        returnValue: _i8.Future<_i6.AppConfig>.value(_FakeAppConfig_4(
          this,
          Invocation.method(
            #createConfig,
            [
              instanceId,
              transformSeed,
              masterSeed,
              masterPassword,
              secretKey,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i6.AppConfig>.value(_FakeAppConfig_4(
          this,
          Invocation.method(
            #createConfig,
            [
              instanceId,
              transformSeed,
              masterSeed,
              masterPassword,
              secretKey,
            ],
          ),
        )),
      ) as _i8.Future<_i6.AppConfig>);

  @override
  _i8.Future<String> saveConfig(_i6.AppConfig? config) => (super.noSuchMethod(
        Invocation.method(
          #saveConfig,
          [config],
        ),
        returnValue: _i8.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #saveConfig,
            [config],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #saveConfig,
            [config],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i4.ProtectedValue?> readSecureStore(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #readSecureStore,
          [key],
        ),
        returnValue: _i8.Future<_i4.ProtectedValue?>.value(),
        returnValueForMissingStub: _i8.Future<_i4.ProtectedValue?>.value(),
      ) as _i8.Future<_i4.ProtectedValue?>);

  @override
  _i8.Future<void> saveSecureStore(
    String? key,
    _i4.ProtectedValue? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSecureStore,
          [
            key,
            data,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i10.Uint8List> generateEmergencyKit(String? secretKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateEmergencyKit,
          [secretKey],
        ),
        returnValue: _i8.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
        returnValueForMissingStub:
            _i8.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
      ) as _i8.Future<_i10.Uint8List>);
}
