// Mocks generated by Mockito 5.4.5 from annotations
// in cryptowl/test/services/app_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i2;

import 'package:cryptowl/src/config/meta.dart' as _i4;
import 'package:cryptowl/src/service/file_service.dart' as _i5;
import 'package:cryptowl/src/service/kdbx_service.dart' as _i7;
import 'package:kdbx/kdbx.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFile_0 extends _i1.SmartFake implements _i2.File {
  _FakeFile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKdbxFile_1 extends _i1.SmartFake implements _i3.KdbxFile {
  _FakeKdbxFile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMeta_2 extends _i1.SmartFake implements _i4.Meta {
  _FakeMeta_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileService extends _i1.Mock implements _i5.FileService {
  @override
  _i6.Future<_i2.File> getConfigFile() =>
      (super.noSuchMethod(
            Invocation.method(#getConfigFile, []),
            returnValue: _i6.Future<_i2.File>.value(
              _FakeFile_0(this, Invocation.method(#getConfigFile, [])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.File>.value(
              _FakeFile_0(this, Invocation.method(#getConfigFile, [])),
            ),
          )
          as _i6.Future<_i2.File>);

  @override
  _i6.Future<bool> hasConfigFile() =>
      (super.noSuchMethod(
            Invocation.method(#hasConfigFile, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [KdbxService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKdbxService extends _i1.Mock implements _i7.KdbxService {
  @override
  _i6.Future<_i3.KdbxFile> create(_i3.ProtectedValue? masterPassword) =>
      (super.noSuchMethod(
            Invocation.method(#create, [masterPassword]),
            returnValue: _i6.Future<_i3.KdbxFile>.value(
              _FakeKdbxFile_1(
                this,
                Invocation.method(#create, [masterPassword]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.KdbxFile>.value(
              _FakeKdbxFile_1(
                this,
                Invocation.method(#create, [masterPassword]),
              ),
            ),
          )
          as _i6.Future<_i3.KdbxFile>);

  @override
  _i6.Future<_i4.Meta> loadMeta(_i3.KdbxFile? kdbx) =>
      (super.noSuchMethod(
            Invocation.method(#loadMeta, [kdbx]),
            returnValue: _i6.Future<_i4.Meta>.value(
              _FakeMeta_2(this, Invocation.method(#loadMeta, [kdbx])),
            ),
            returnValueForMissingStub: _i6.Future<_i4.Meta>.value(
              _FakeMeta_2(this, Invocation.method(#loadMeta, [kdbx])),
            ),
          )
          as _i6.Future<_i4.Meta>);
}
