// Mocks generated by Mockito 5.4.6 from annotations
// in cryptowl/test/services/password_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;
import 'dart:typed_data' as _i15;

import 'package:cryptowl/src/config/app_config.dart' as _i7;
import 'package:cryptowl/src/crypto/aead_crypto.dart' as _i4;
import 'package:cryptowl/src/crypto/argon2.dart' as _i3;
import 'package:cryptowl/src/crypto/hkdf.dart' as _i2;
import 'package:cryptowl/src/crypto/protected_value.dart' as _i6;
import 'package:cryptowl/src/database/database.dart' as _i12;
import 'package:cryptowl/src/domain/password.dart' as _i11;
import 'package:cryptowl/src/repositories/password_repository.dart' as _i16;
import 'package:cryptowl/src/service/config_service.dart' as _i5;
import 'package:cryptowl/src/service/kdf_service.dart' as _i13;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i10;
import 'package:logging/logging.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:uuid/uuid.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCryptoGraphyHkdf_0 extends _i1.SmartFake
    implements _i2.CryptoGraphyHkdf {
  _FakeCryptoGraphyHkdf_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNativeArgon2_1 extends _i1.SmartFake implements _i3.NativeArgon2 {
  _FakeNativeArgon2_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCryptographyAesGcm_2 extends _i1.SmartFake
    implements _i4.CryptographyAesGcm {
  _FakeCryptographyAesGcm_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfigService_3 extends _i1.SmartFake implements _i5.ConfigService {
  _FakeConfigService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProtectedValue_4 extends _i1.SmartFake
    implements _i6.ProtectedValue {
  _FakeProtectedValue_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthEncryptedResult_5 extends _i1.SmartFake
    implements _i4.AuthEncryptedResult {
  _FakeAuthEncryptedResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppConfig_6 extends _i1.SmartFake implements _i7.AppConfig {
  _FakeAppConfig_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogger_7 extends _i1.SmartFake implements _i8.Logger {
  _FakeLogger_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUuid_8 extends _i1.SmartFake implements _i9.Uuid {
  _FakeUuid_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRef_9<State extends Object?> extends _i1.SmartFake
    implements _i10.Ref<State> {
  _FakeRef_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePassword_10 extends _i1.SmartFake implements _i11.Password {
  _FakePassword_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSqliteDb_11 extends _i1.SmartFake implements _i12.SqliteDb {
  _FakeSqliteDb_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KdfService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKdfService extends _i1.Mock implements _i13.KdfService {
  @override
  _i2.CryptoGraphyHkdf get hkdf => (super.noSuchMethod(
        Invocation.getter(#hkdf),
        returnValue: _FakeCryptoGraphyHkdf_0(
          this,
          Invocation.getter(#hkdf),
        ),
        returnValueForMissingStub: _FakeCryptoGraphyHkdf_0(
          this,
          Invocation.getter(#hkdf),
        ),
      ) as _i2.CryptoGraphyHkdf);

  @override
  _i3.NativeArgon2 get argon2 => (super.noSuchMethod(
        Invocation.getter(#argon2),
        returnValue: _FakeNativeArgon2_1(
          this,
          Invocation.getter(#argon2),
        ),
        returnValueForMissingStub: _FakeNativeArgon2_1(
          this,
          Invocation.getter(#argon2),
        ),
      ) as _i3.NativeArgon2);

  @override
  _i4.CryptographyAesGcm get aeadCrypto => (super.noSuchMethod(
        Invocation.getter(#aeadCrypto),
        returnValue: _FakeCryptographyAesGcm_2(
          this,
          Invocation.getter(#aeadCrypto),
        ),
        returnValueForMissingStub: _FakeCryptographyAesGcm_2(
          this,
          Invocation.getter(#aeadCrypto),
        ),
      ) as _i4.CryptographyAesGcm);

  @override
  _i5.ConfigService get configService => (super.noSuchMethod(
        Invocation.getter(#configService),
        returnValue: _FakeConfigService_3(
          this,
          Invocation.getter(#configService),
        ),
        returnValueForMissingStub: _FakeConfigService_3(
          this,
          Invocation.getter(#configService),
        ),
      ) as _i5.ConfigService);

  @override
  _i14.Future<_i6.ProtectedValue> createTransformedMasterKey(
    _i6.ProtectedValue? masterPassword,
    _i6.ProtectedValue? secretKey,
    _i15.Uint8List? salt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTransformedMasterKey,
          [
            masterPassword,
            secretKey,
            salt,
          ],
        ),
        returnValue:
            _i14.Future<_i6.ProtectedValue>.value(_FakeProtectedValue_4(
          this,
          Invocation.method(
            #createTransformedMasterKey,
            [
              masterPassword,
              secretKey,
              salt,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i6.ProtectedValue>.value(_FakeProtectedValue_4(
          this,
          Invocation.method(
            #createTransformedMasterKey,
            [
              masterPassword,
              secretKey,
              salt,
            ],
          ),
        )),
      ) as _i14.Future<_i6.ProtectedValue>);

  @override
  _i14.Future<_i6.ProtectedValue> createStretchedMasterKey(
    _i6.ProtectedValue? transformedMasterKey,
    _i15.Uint8List? instanceId,
    _i15.Uint8List? masterSeed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStretchedMasterKey,
          [
            transformedMasterKey,
            instanceId,
            masterSeed,
          ],
        ),
        returnValue:
            _i14.Future<_i6.ProtectedValue>.value(_FakeProtectedValue_4(
          this,
          Invocation.method(
            #createStretchedMasterKey,
            [
              transformedMasterKey,
              instanceId,
              masterSeed,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i6.ProtectedValue>.value(_FakeProtectedValue_4(
          this,
          Invocation.method(
            #createStretchedMasterKey,
            [
              transformedMasterKey,
              instanceId,
              masterSeed,
            ],
          ),
        )),
      ) as _i14.Future<_i6.ProtectedValue>);

  @override
  _i14.Future<_i4.AuthEncryptedResult> createProtectedSymmetricKey(
    _i6.ProtectedValue? symmetricKey,
    _i6.ProtectedValue? stretchedMasterKey,
    _i15.Uint8List? nonce,
    _i15.Uint8List? instanceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProtectedSymmetricKey,
          [
            symmetricKey,
            stretchedMasterKey,
            nonce,
            instanceId,
          ],
        ),
        returnValue: _i14.Future<_i4.AuthEncryptedResult>.value(
            _FakeAuthEncryptedResult_5(
          this,
          Invocation.method(
            #createProtectedSymmetricKey,
            [
              symmetricKey,
              stretchedMasterKey,
              nonce,
              instanceId,
            ],
          ),
        )),
        returnValueForMissingStub: _i14.Future<_i4.AuthEncryptedResult>.value(
            _FakeAuthEncryptedResult_5(
          this,
          Invocation.method(
            #createProtectedSymmetricKey,
            [
              symmetricKey,
              stretchedMasterKey,
              nonce,
              instanceId,
            ],
          ),
        )),
      ) as _i14.Future<_i4.AuthEncryptedResult>);

  @override
  _i14.Future<_i6.ProtectedValue> generateRandomBytes({int? length = 32}) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateRandomBytes,
          [],
          {#length: length},
        ),
        returnValue:
            _i14.Future<_i6.ProtectedValue>.value(_FakeProtectedValue_4(
          this,
          Invocation.method(
            #generateRandomBytes,
            [],
            {#length: length},
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i6.ProtectedValue>.value(_FakeProtectedValue_4(
          this,
          Invocation.method(
            #generateRandomBytes,
            [],
            {#length: length},
          ),
        )),
      ) as _i14.Future<_i6.ProtectedValue>);

  @override
  _i14.Future<_i7.AppConfig> generateAppConfig(
    _i6.ProtectedValue? masterPassword,
    _i6.ProtectedValue? secretKey,
    String? instanceId,
    _i15.Uint8List? transformSeed,
    _i15.Uint8List? masterSeed,
    _i6.ProtectedValue? symmetricKey,
    _i15.Uint8List? nonce,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAppConfig,
          [
            masterPassword,
            secretKey,
            instanceId,
            transformSeed,
            masterSeed,
            symmetricKey,
            nonce,
          ],
        ),
        returnValue: _i14.Future<_i7.AppConfig>.value(_FakeAppConfig_6(
          this,
          Invocation.method(
            #generateAppConfig,
            [
              masterPassword,
              secretKey,
              instanceId,
              transformSeed,
              masterSeed,
              symmetricKey,
              nonce,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i7.AppConfig>.value(_FakeAppConfig_6(
          this,
          Invocation.method(
            #generateAppConfig,
            [
              masterPassword,
              secretKey,
              instanceId,
              transformSeed,
              masterSeed,
              symmetricKey,
              nonce,
            ],
          ),
        )),
      ) as _i14.Future<_i7.AppConfig>);

  @override
  _i14.Future<_i6.ProtectedValue> decryptSymmetricKey(
    _i6.ProtectedValue? masterPassword,
    _i6.ProtectedValue? secretKey,
    _i7.AppConfig? config,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptSymmetricKey,
          [
            masterPassword,
            secretKey,
            config,
          ],
        ),
        returnValue:
            _i14.Future<_i6.ProtectedValue>.value(_FakeProtectedValue_4(
          this,
          Invocation.method(
            #decryptSymmetricKey,
            [
              masterPassword,
              secretKey,
              config,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i6.ProtectedValue>.value(_FakeProtectedValue_4(
          this,
          Invocation.method(
            #decryptSymmetricKey,
            [
              masterPassword,
              secretKey,
              config,
            ],
          ),
        )),
      ) as _i14.Future<_i6.ProtectedValue>);
}

/// A class which mocks [PasswordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPasswordRepository extends _i1.Mock
    implements _i16.PasswordRepository {
  @override
  _i8.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_7(
          this,
          Invocation.getter(#logger),
        ),
        returnValueForMissingStub: _FakeLogger_7(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i8.Logger);

  @override
  _i9.Uuid get uuid => (super.noSuchMethod(
        Invocation.getter(#uuid),
        returnValue: _FakeUuid_8(
          this,
          Invocation.getter(#uuid),
        ),
        returnValueForMissingStub: _FakeUuid_8(
          this,
          Invocation.getter(#uuid),
        ),
      ) as _i9.Uuid);

  @override
  _i10.Ref<Object?> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeRef_9<Object?>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub: _FakeRef_9<Object?>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i10.Ref<Object?>);

  @override
  _i14.Future<List<_i11.PasswordBasic>> list() => (super.noSuchMethod(
        Invocation.method(
          #list,
          [],
        ),
        returnValue:
            _i14.Future<List<_i11.PasswordBasic>>.value(<_i11.PasswordBasic>[]),
        returnValueForMissingStub:
            _i14.Future<List<_i11.PasswordBasic>>.value(<_i11.PasswordBasic>[]),
      ) as _i14.Future<List<_i11.PasswordBasic>>);

  @override
  _i14.Future<_i11.Password> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i14.Future<_i11.Password>.value(_FakePassword_10(
          this,
          Invocation.method(
            #findById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i11.Password>.value(_FakePassword_10(
          this,
          Invocation.method(
            #findById,
            [id],
          ),
        )),
      ) as _i14.Future<_i11.Password>);

  @override
  _i14.Future<bool> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i14.Future<bool>.value(false),
        returnValueForMissingStub: _i14.Future<bool>.value(false),
      ) as _i14.Future<bool>);

  @override
  _i14.Future<void> create(
    _i12.TPasswordData? passwordEntity,
    _i12.TDataEncryptKeyData? dekEntity,
    _i12.TEncryptedDataData? encryptedDataEntity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            passwordEntity,
            dekEntity,
            encryptedDataEntity,
          ],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> update(
    String? id, {
    required String? title,
    required _i6.ProtectedValue? value,
    required String? username,
    required String? url,
    required String? remark,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [id],
          {
            #title: title,
            #value: value,
            #username: username,
            #url: url,
            #remark: remark,
          },
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<_i12.SqliteDb> requireDb() => (super.noSuchMethod(
        Invocation.method(
          #requireDb,
          [],
        ),
        returnValue: _i14.Future<_i12.SqliteDb>.value(_FakeSqliteDb_11(
          this,
          Invocation.method(
            #requireDb,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i14.Future<_i12.SqliteDb>.value(_FakeSqliteDb_11(
          this,
          Invocation.method(
            #requireDb,
            [],
          ),
        )),
      ) as _i14.Future<_i12.SqliteDb>);
}
