package com.typedefai.cryptowl.vault

import com.typedefai.cryptowl.crypto.ProtectedValue
import java.io.File
import javax.crypto.AEADBadTagException
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * CWO1 codec tests. The `cwo1_whole.bin` / `cwo1_chunked.bin` vectors were
 * generated by `wechat_sns_export/migrate_moments.py` (the cross-verification
 * oracle) with fixed FEK = 0x66*32 and AAD = the media row id below — the
 * Android codec must decrypt them byte-exact.
 */
class Cwo1Test {

    private val fek = ProtectedValue.fromBinary(ByteArray(32) { 0x66 })
    private val aad = "a9b7c4d2-0000-4f00-9000-000000000001".toByteArray()

    private fun vector(name: String): ByteArray =
        File("src/test/resources/vectors/$name").readBytes()

    @Test
    fun `decrypts the python whole-file vector`() {
        val data = vector("cwo1_whole.bin")
        assertEquals("CWO1", data.decodeToString(0, 4))

        val plain = Cwo1.decryptWholeFile(fek, aad, data)

        assertEquals("the quick brown fox jumps over the lazy dog 0123456789", plain.decodeToString())
    }

    @Test
    fun `decrypts the python chunked vector`() {
        val data = vector("cwo1_chunked.bin")
        val header = Cwo1.parseHeader(data)
        assertEquals(Cwo1.VERSION, header.version)
        assertEquals(Cwo1.CHUNK_SIZE, header.chunkSize)
        assertEquals(2, header.chunkCount)
        assertTrue(header.isChunked)
        assertEquals(76854, data.size)

        val expected = ByteArray(76800) { (it % 256).toByte() }
        // random access: each chunk decrypts independently
        val chunk0 = Cwo1.decryptChunkAt(fek, aad, data, 0)
        val chunk1 = Cwo1.decryptChunkAt(fek, aad, data, 1)
        assertEquals(65536, chunk0.size)
        assertEquals(11264, chunk1.size)
        assertArrayEquals(expected.copyOfRange(0, 65536), chunk0)
        assertArrayEquals(expected.copyOfRange(65536, 76800), chunk1)
        assertArrayEquals(expected, Cwo1.decryptChunked(fek, aad, data))
    }

    @Test
    fun `whole-file round trip`() {
        val plain = "some image bytes".toByteArray()
        val encrypted = Cwo1.encryptWholeFile(fek, aad, plain)

        assertArrayEquals(plain, Cwo1.decryptWholeFile(fek, aad, encrypted))
        assertEquals(Cwo1.HEADER_LEN + plain.size + Cwo1.TAG_SIZE, encrypted.size)
        assertFalse(Cwo1.parseHeader(encrypted).isChunked)
    }

    @Test
    fun `chunked round trip with random access`() {
        val plain = ByteArray(200_000) { (it * 7 % 256).toByte() }
        val encrypted = Cwo1.encryptChunked(fek, aad, plain)
        val header = Cwo1.parseHeader(encrypted)
        assertEquals(4, header.chunkCount)

        for (i in 0L until header.chunkCount) {
            val start = (i * Cwo1.CHUNK_SIZE).toInt()
            val end = minOf((i + 1) * Cwo1.CHUNK_SIZE, plain.size.toLong()).toInt()
            assertArrayEquals(plain.copyOfRange(start, end), Cwo1.decryptChunkAt(fek, aad, encrypted, i))
        }
        assertArrayEquals(plain, Cwo1.decryptChunked(fek, aad, encrypted))
    }

    @Test
    fun `empty whole-file payload`() {
        val encrypted = Cwo1.encryptWholeFile(fek, aad, ByteArray(0))
        assertEquals(0, Cwo1.decryptWholeFile(fek, aad, encrypted).size)
    }

    @Test(expected = AEADBadTagException::class)
    fun `tampered whole-file payload rejected`() {
        val encrypted = Cwo1.encryptWholeFile(fek, aad, "secret".toByteArray())
        encrypted[30] = (encrypted[30].toInt() xor 0xff).toByte()
        Cwo1.decryptWholeFile(fek, aad, encrypted)
    }

    @Test(expected = AEADBadTagException::class)
    fun `wrong aad rejected`() {
        val encrypted = Cwo1.encryptWholeFile(fek, aad, "secret".toByteArray())
        Cwo1.decryptWholeFile(fek, aad, encrypted) // ok
        Cwo1.decryptWholeFile(fek, "other-row-id".toByteArray(), encrypted)
    }

    @Test(expected = IllegalArgumentException::class)
    fun `wrong magic rejected`() {
        val encrypted = Cwo1.encryptWholeFile(fek, aad, "secret".toByteArray())
        encrypted[0] = 'X'.code.toByte()
        Cwo1.parseHeader(encrypted)
    }

    @Test
    fun `header offsets match the documented layout`() {
        val data = vector("cwo1_chunked.bin")
        // record 0 starts at 22; record 1 at 22 + (65536 + 16)
        val header = Cwo1.parseHeader(data)
        val expectedOffset = Cwo1.HEADER_LEN + 1 * header.recordLength
        val chunk1 = Cwo1.decryptChunkAt(fek, aad, data, 1)
        // re-parse from the raw bytes at the computed offset as a sanity check
        val raw = data.copyOfRange(expectedOffset, data.size)
        assertEquals(11264 + Cwo1.TAG_SIZE, raw.size)
        assertTrue(chunk1.isNotEmpty())
    }
}
