name: Run Tests
run-name: Unit test🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.4
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: |
          cd deps/native_argon2/src && mkdir build && cd build && cmake .. && make
      - run: |
          cp deps/native_sqlcipher/src && mkdir build && cd build && cmake .. && make
      - run: |
          cp -R ./assets/dict /tmp/
          mkdir /tmp/sqlcipher-build
          cp deps/native_sqlcipher/src/build/*.so /tmp/sqlcipher-build/
      - run: flutter test