name: Run Tests
run-name: ${{ github.actor }} running tests 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.4
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
